spring:
  main:
    web-application-type: none
    
server:  ssl:
    trust-store-type: pkcs12    trust-store: file:C:/Users/kwong/Documents/certs/selfsigned/ca/trust.p12
    trust-store-password: abcd1234
     